# apps/cert-manager/crds.yaml
# This file tells Argo CD to apply the CRDs first
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-crds
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/sync-wave: "1"
data:
  apply-crds.sh: |
    #!/bin/sh
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
