# apps/cert-manager/deployment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Resource patches to optimize for your VM
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-patches
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  patches.yaml: |
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 200Mi
