# apps/cert-manager/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Since Argo CD has issues with remote URLs in Kustomize,
# we'll have Argo CD apply the cert-manager.yaml directly

resources:
  - clusterissuer.yaml

