# apps/cert-manager/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  - clusterissuer.yaml

# Apply patches to reduce resource usage
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cert-manager
      namespace: cert-manager
    spec:
      template:
        spec:
          containers:
          - name: cert-manager-controller
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 200Mi
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cert-manager-webhook
      namespace: cert-manager
    spec:
      template:
        spec:
          containers:
          - name: cert-manager-webhook
            resources:
              requests:
                cpu: 20m
                memory: 50Mi
              limits:
                cpu: 50m
                memory: 100Mi
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cert-manager-cainjector
      namespace: cert-manager
    spec:
      template:
        spec:
          containers:
          - name: cert-manager-cainjector
            resources:
              requests:
                cpu: 20m
                memory: 50Mi
              limits:
                cpu: 50m
                memory: 100Mi
